### PR TITLE
changed  admx template version number & released date

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #725 , so i changed old version to  4993.1000  and the corresponding date
Seen below site 
**https://www.microsoft.com/en-us/download/details.aspx?id=49030**

### CODE REVIEW

**Comment by RAJU2529** [comment]
@illfated .Please review this PR

**Comment by manoth-msft** [comment]
The article mentioned "at **least** version 48xx.xxx", so there is no need to update the article.

**Comment by RAJU2529** [comment]
@manoth-msft . thanks for the comment.
Are you from Microsoft? . msft is  mentioned in your name

**Comment by DHB-MSFT** [comment]
As @manoth-msft noted, article says "at least" so article is correct as is.

**Pull request closed without merging**
