### PR TITLE
previous link to Office compat matrix outdated

### PR DESCRIPTION
**Pull request by Karl-WE**
included the latest link. Please #signoff asap, to avoid confusion at customers and potentially wrong investment decisions in regard of EOS and support of Office 365 on Windows Server 2022 @v-dihans  

Your link does not even include Windows Server 2022. TYVM Diana!

### CODE REVIEW

**Comment by DHB-MSFT** [comment]
@Karl-WE   We're aware of this issue and a resolution is being worked on. Depending on how long that takes, we'll decide whether we need to temporarily update all URL references for the matrix to point to the English version (of Sept 2021) until the resolution is in place.

**Comment by Karl-WE** [comment]
@DHB-MSFT Thanks for your reply and triage. Why do you think it is not a good idea to update this link to this one? It is often published. The only thing that is different there is no aka.ms or fwlink for this yet (as of I know).

As a Microsoft Partner It is important that this gets an update so we can plan and budget for changes with our customers for 2025. Thank you very much for elaborating the close.

**Comment by DHB-MSFT** [comment]
@Karl-WE  We've gone ahead and temporarily changed the URL for the matrix in our articles from https://go.microsoft.com/fwlink/p/?linkid=2111390 to https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI. But that means for the time being, everyone will only see the English version of the matrix, but at least it will be the most current version of the matrix.

(It might take a few days for our localization process to pick up and implement this change to the URL in the articles.)

Once we get the issue resolved with the localized versions of the matrix, we'll revert back to using https://go.microsoft.com/fwlink/p/?linkid=2111390 in our articles so that customers will once again be taken to the appropriate localized version of the matrix, where available.

**Comment by Karl-WE** [comment]
Thank you for your understanding.

Due to the nature of localization most of the time the non en-us content on docs.microsoft.com or KB articles are either outdated or has wrong links or outdated downloads.

I am thankful so many contribute to and spent precious time on a human translation of articles 

Appreciate your action and decision to merge this for the moment as primarily the en-us content is prefered by professionals anyway for said reason.

If you need help with a de-de localization I am happy to help.

**Comment by Karl-WE** [comment]
PS @DHB-MSFT this one appear unmerged, means there was an internal PR?

**Comment by DHB-MSFT** [comment]
@Karl-WE  We did an internal PR because there were several articles where we needed to make this change.

**Comment by Karl-WE** [comment]
Ah I see thank you very much once again. 👍🏻

**Pull request closed without merging**
