### PR TITLE
1justingilmore seo working branch

### PR DESCRIPTION
**Pull request by 1justingilmore**

### CODE REVIEW

**Comment by DHB-MSFT** [comment]
@1justingilmore -- can you provide some context of why you are making these changes?  I see the title references SEO, but all of these topics are hidden from search engines, so I'm not sure why we'd be trying to optimize them for SEO.  Thanks.

**Comment by 1justingilmore** [comment]
These are for Marvel Seo updates.

**Comment by 1justingilmore** [comment]
Working with Dani Halfin <Dani.Halfin@microsoft.com>

**Comment by 1justingilmore** [comment]
These topics are not indexed. Closing pull request.

**Pull request closed without merging**
